version: '3.5'


services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '${DB_PORT}:5432'

volumes:
  postgres-db:
    driver: local