export const DATABASE_PROVIDER = 'DATA_SOURCE';
export const USER_PROVIDER = 'USER_REPOSITORY';
export const TASK_PROVIDER = 'TASK_REPOSITORY';
export const CATEGORY_PROVIDER = 'CATEGORY_REPOSITORY';
export const CONNECTION_TIMEOUT_IN_SECONDS = 10;
